### ISSUE TITLE
Service starting procedure and using port 8080

### ISSUE THREAD

**Issue by cmonty14** [JakubStas/dev-utils#2]
Hello!
I have installed this in Debian 9.
All dependencies are installed incl. npm 5.8.0 from unstable.

npm install -g json
easy_install pygments
finished w/o error.

However, I cannot execute the referenced commands
jcurl -gX GET http://localhost:8080/Spring4WithSwagger/rest/api-docs/
because no service is listening on port 8080.

```
root@ct-204-prettycurl:~# netstat -tulpen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Benutzer   Inode      PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          39028925   2037/sshd
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      0          39043713   11084/sshd: root@pt
tcp6       0      0 :::22                   :::*                    LISTEN      0          39028934   2037/sshd
tcp6       0      0 ::1:6010                :::*                    LISTEN      0          39043712   11084/sshd: root@pt
```

Actually port 8080 is used for proxy (server is running behind corporate proxy).

**Question:**
How can I start the webservice PrettyCurl?
How can I modify the port?

THX

**Comment by JakubStas** [comment]
Hi @74cmonty, I believe you are mixing two separate things here. Sounds to me, like you were able to install and configure your `jcurl` alias correctly. But keep in mind that this alias is only decorating the good old fashioned curl calls and makes the output more readable. The URL there is from one of my other projects and I was only using it to demo the effects of this alias.

Having said that, I encourage you to try something like this on publicly accessible endpoints as of writing this comment.

`jcurl https://jsonplaceholder.typicode.com/todos/1`

`xcurl http://luasforecasts.rpa.ie/xml/get.ashx?action=forecast&stop=ran&encrypt=false`

**Comment by cmonty14** [comment]
Hi,
probably I totally misunderstood the function of this project.
I was looking for a service that generates JSON pretty print like [this](https://jsonprettyprint.org/) but on a local server.

Are you providing this service with your project?

THX

**Comment by JakubStas** [comment]
Yeah, that is not what it does at all. But you should be able to achieve that in most programming languages I would say. Having it exposed as a callable API should be trivial as well.
